### ISSUE TITLE
Comments / Descriptions

### ISSUE THREAD

**Issue by alpox** [graphql-go/graphql#116]
I am currently working on a module for generating a graphql-go/graphql schema from the type definition of the graphql language on [graphql-go-gen](https://github.com/alpox/graphql-go-gen).
For doing that i am using the parser from this project which parses the system but doesnt make use of it.
Now I wanted to integrate the descriptions for the types. Other projects like mine make use of the comment tags which are prefixed by a # in graphql but it seems these don't even get parsed in this project? It would be great if you could implement this.
Keep up the good work!

**Comment by chris-ramon** [comment]
Hi @alpox!, thumbs up for `graphql-go-gen` pretty useful project :+1: & really looking forward to try it out.

In regards `graphql/language/parser/parser.go` ignoring comments, I think its the expected behavior, the next following points confirms it, which are based on the [`graphql-js`](github.com/graphql/graphql-js) reference implementation:

- There is not a comment `TokenKind` listed on the possible [tokens](https://github.com/graphql/graphql-js/blob/master/src/language/lexer.js#L91-L108).

- `readToken` from `graphql-js/src/language/lexer.js` ignores comments:
  >  `This skips over whitespace and comments until it finds the next lexable token ...`
  
  > Source: [https://github.com/graphql/graphql-js/blob/master/src/language/lexer.js#L139](https://github.com/graphql/graphql-js/blob/master/src/language/lexer.js#L139)

- There is a [test](https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/lexer.js#L59)  for `graphql-js/src/language/lexer.js` which effectively includes comments on the query and they are ignored by the lexer & parser.

One workaround would be to copy [`lexer`](https://github.com/graphql-go/graphql/blob/master/language/lexer/lexer.go) & [`parser`](https://github.com/graphql-go/graphql/blob/master/language/parser/parser.go) and include those to `graphql-go-gen`, then extend their functionality to not ignore comments, perhaps starting from [`func positionAfterWhitespace(body string, startPosition int) int { ... }`](https://github.com/graphql-go/graphql/blob/master/language/lexer/lexer.go#L419), similar to `github.com/ForbesLindesay/graphql-schema-gen` [`strategy`](https://github.com/ForbesLindesay/graphql-schema-gen/blob/master/src/parser.js#L227).

Keep it up the great work!

**Comment by alpox** [comment]
Thanks @chris-ramon for your response. I will try to do like you suggested. It could take me a while to finish since i'm quite busy these days and i'm not familiar with compilers :smiley: I'll try my best!

**Comment by chris-ramon** [comment]
Alright @alpox, take it easy, keep up the great work and feel free to re-open the issue as needed.
