### ISSUE TITLE
lexer: custom charset for names

### ISSUE THREAD

**Issue by dennwc** [graphql-go/graphql#153]
Is there a chance that the change to accept non-standard characters in names would be accepted?

We at [Cayley](https://github.com/cayleygraph/cayley) want to integrate GraphQL as a query language natively (using parser from this great library), but the charset in names is to restrictive for our model.

Thus I'm wondering, should I try to push a PR, or I'll have to maintain a separate fork?

Thanks!

**Comment by chris-ramon** [comment]
Hi @dennwc, sounds great about considering use the parser of `graphql-go/graphql`! :star2: ; could you expand on `charset in names is to restrictive`?

**Comment by dennwc** [comment]
[lexer.go#L107](https://github.com/graphql-go/graphql/blob/master/language/lexer/lexer.go#L107) this function accepts `[_A-Za-z][_0-9A-Za-z]*` charset. We wants to expand it a bit with some special characters, as `<>/.:`. This is not the right behavior according to GraphQL spec, but it would be nice if lexer can be switched to some custom charset on-demand.

**Comment by chris-ramon** [comment]
Got it, well effectively GraphQL spec says: names are limited to `/[_A-Za-z][_0-9A-Za-z]*/` in order to support interoperation with as many as other systems as possible: [source](https://facebook.github.io/graphql/#sec-Names).

Also they are not considering adding other special characters like `$` for example, reference [here](https://github.com/facebook/graphql/issues/102).

Said that, I think we cannot help directly here, since we are following the GraphQL spec, I'd suggest to fork the parser and customize it to `Cayley`'s needs, looking forward to see it landing to the project :+1:.

**Comment by dennwc** [comment]
Sure. Thanks anyway!

And to clarify, I was not asking to change parser behavior, just to expose some sort of hook to be able to alter it.
