### ISSUE TITLE
List of type as mutation argument

### ISSUE THREAD

**Issue by paulinate** [graphql-go/graphql#186]
Hi!

I'm having the following problem when trying to specify this mutation:

`input CreateInput {
	clientMutationID: string!
	startDate: string!
	level: LevelType
	classifications: [Classification]
}`

Unfortunately I'm unable to make the "classifications" field to properly work. For some reason, when I send the mutation the server-side always receives the following as input for that field:

[]interface {}{interface {}(nil)} 

The Classification type is defined as follows:

`classificationDefinition := graphql.NewObject(graphql.ObjectConfig{
		Name:        "Classification",
		Description: "Classification of the event.",
		Fields: graphql.Fields{
			"name": &graphql.Field{
				Type:        graphql.String,
				Description: "Classification name.",
			},
		},
	})`

And inside of the InputFields from the event (relay.MutationWichClientMutationID since i'm using relay-go), i'm declaring the input field as:

`"classifications": &graphql.InputObjectFieldConfig{
		Type: graphql.NewList(classificationDefinition),
},`

Any help with this or with any other example of a mutation using a list of type argument would be greatly appreciated!

**Comment by sfriedel** [comment]
@paulinate I think the problem is that you are trying to use a `graphql.Object` as an input value. That is not possible, instead all inputs have to be either `graphql.Scalar` or `graphql.InputObject` values.

What you should do is define a new GraphQL type using `graphql.NewInputObject` that mirrors your `classificationDefinition` and use that instead.

You may also find [this part of the GraphQL spec](https://facebook.github.io/graphql/#sec-Input-Objects) interesting because it explains the reasoning for having separate Object and InputObject representations.

> The Object type defined above is inappropriate for re‐use here, because Objects can contain fields that express circular references or references to interfaces and unions, neither of which is appropriate for use as an input argument. For this reason, input objects have a separate type in the system.

**Comment by paulinate** [comment]
@sfriedel You were completely right!

That was the issue I was experiencing. I assumed that using a graphql.Object in that context made sense, but wasn't really aware of the GraphQL spec you are referring.

Many thanks!
