### ISSUE TITLE
GraphiQL fails on introspection

### ISSUE THREAD

**Issue by arv** [graphql-go/graphql#187]
I'm getting the following error:

```json
{
  "data": null,
  "errors": [
    {
      "message": "Unknown type \"__Type\".",
      "locations": [
        {
          "line": 1,
          "column": 283
        }
      ]
    },
    {
      "message": "Unknown type \"__InputValue\".",
      "locations": [
        {
          "line": 1,
          "column": 769
        }
      ]
    },
    {
      "message": "Unknown type \"__Type\".",
      "locations": [
        {
          "line": 1,
          "column": 870
        }
      ]
    }
  ]
}
```

when using the GraphiQL UI. Any hints on where to start to track this down?

**Comment by incu6us** [comment]
Hi @arv,
It happens because you have a duplicated graphql.Object names in your Schema

**Comment by arv** [comment]
Thanks. I'll look into how we generate our types...

**Comment by vergenzt** [comment]
FYI @arv I encountered identical symptoms and for me it ended up being caused by using the "wrong" type when defining fields on the InputObject. (I was using `graphql.Fields{ ... }`; turns out I was supposed to be using `graphql.InputObjectConfigFieldMap{ ... }` for InputObjects specifically.) The problem went away for me when I fixed that.

I filed #256 to raise a flag that that scenario really should have failed at compile time.

**Comment by arv** [comment]
@vergenzt in our case we did generate the same name more than once. In our system we ended up including a hash of the type in the type name. Ugly but it was the only way to guarantee uniqueness.

**Comment by sntiagoma** [comment]
Hi @incu6us 
There's a way to know which field(s) is the cause of the error? I checked all Name fields and There isn't duplicated names.

**Comment by limoli** [comment]
I am getting the same problem, but with a different behaviour.
I want to create a schema which has **only mutation field**. It doesn't need query field.
```go
var Schema, _ = graphql.NewSchema(graphql.SchemaConfig{
	Mutation: rootMutation,
})
```
In this way, **graphiql** browser mode gets the following error from graphql:
```json
{
  "data": null,
  "errors": [
    {
      "message": "Unknown type \"__Type\".",
      "locations": [
        {
          "line": 20,
          "column": 24
        }
      ]
    },
    {
      "message": "Unknown type \"__InputValue\".",
      "locations": [
        {
          "line": 53,
          "column": 26
        }
      ]
    },
    {
      "message": "Unknown type \"__Type\".",
      "locations": [
        {
          "line": 60,
          "column": 23
        }
      ]
    }
  ]
}
```
So, documentation loads nothing (no schemas).

**Comment by padunk** [comment]
I have a similar issue too, turn out that Name in graphql.ObjectConfig must be PascalCase or camelCase.
I can't write Name like `User Definition`, it must be `UserDefinition`.

**Comment by florianlenz** [comment]
And the `Name` property needs to be set. Is there a reason why there are no checks for if the `Name` property is set on an object @sogko @chris-cp? I would put in the effort of creating a pull request thats adds a check for the name if there is no reason for not doing so. Is this project still maintained? There are a lot of open PR's.

**Comment by exapsy** [comment]
For the sake of other fellows troubleshooting:

To me it happened because I didn't have `IsTypeOf` on a Type I used in an `Enum`, because types in an `EnumConfig.Types` require to have an implementation of `IsTypeOf`.

It's kinda annoying that the library makes absolutely no effort to help you debug these things, and I kinda wonder if it's still maintained at all as @florianlenz mentioned. Should we move to another library? I would be willing to donate but there's no donate button at all as well.
