### ISSUE TITLE
go graphql schema for data model which contains interface type, nested type

### ISSUE THREAD

**Issue by ChengYuHin99** [graphql-go/graphql#295]
Now I am trying to define go graphql schema for following data structure defined as model.

![image](https://user-images.githubusercontent.com/29444609/37380295-000ca2ae-2773-11e8-944b-54b728f9261d.png)

And Following is go graqhql schema type which i am going to define for above data model. But I am not sure how to define correctly even though i tried to find solution among go-lang documents, also stackoverflow questions.
![image](https://user-images.githubusercontent.com/29444609/37380322-1bced340-2773-11e8-8f40-3b04b456b22a.png)

Please help me this.. I am struggling with this problem all the day, but not found how to do.
Thanks.

**Comment by sfriedel** [comment]
Hi @ChengYuHin99,

directly exposing arbitrary objects using `interface{}` as you did in `value` doesn't work like that in GraphQL. You have to be able to express the structure of the type to be able to expose it. If `value` actually only contains values of one of several types that you know beforehand, you should be able to express that using either GraphQL [Unions](http://facebook.github.io/graphql/October2016/#sec-Unions) or [Interfaces](http://facebook.github.io/graphql/October2016/#sec-Interfaces).

For `properties` the correct type would be `Type: graphql.NewList(propertyType)` or even `graphql.NewList(graphql.NewNonNull(propertyType))`. The problem is that you can't define this in the `ObjectConfig` directly since it would send the Go compiler into a type checking loop. The way to solve this is to first define the `propertyType` without the field for `properties` and afterwards calling

```go
propertyType.AddFieldConfig("properties", &graphql.Field{
	Type: graphql.NewList(propertyType),
})
```

**Comment by ChengYuHin99** [comment]
@sfriedel Hi, thanks for your solution.
As another case, then about args (inputObject), I am going to  define input param as  propertyType. So I am  going to define  with InputObject similar to propertyType define.

![image](https://user-images.githubusercontent.com/29444609/37412000-1325a554-27df-11e8-82d7-59ac9a5a8119.png)

Here, how should I define "properties" field for createPropertyType?
Thanks.

**Comment by sfriedel** [comment]
@ChengYuHin99 I didn't have the need for recursive input objects yet so I'm not sure it the following will work.

It seems the `graphql.InputObject` does not have a `AddFieldConfig` like method but instead it supports specifying the fields as a Thunk (function returning the fields). Theoretically this should allow for recursive field definitions by doing something like this

```go
var createPropertyType *graphql.InputObject

func init() {
	createPropertyType = graphql.NewInputObject(graphql.InputObjectConfig{
		Name: "CreateProperty",
		Fields: func() graphql.InputObjectConfigFieldMap {
			return graphql.InputObjectConfigFieldMap{
				"properties": &graphql.InputObjectFieldConfig{
					Type: createPropertyType,
				},
			}
		},
	})
}
```

Like I said I'm not sure it actually works like this, I didn't have the time to try putting it into a real schema that I could check. Maybe give it a try since I also don't see any alternative approaches except re-thinking the schema to avoid the recursive types on the input.

**Comment by ChengYuHin99** [comment]
@sfriedel Hi.
For InputObject,  recursive define doesn't work. 
Anyway thanks for your kindly answer. 
I will try to find way for avoiding the recursive types on the inputObject.

**Comment by edpark11** [comment]
Hey, FWIW-- I was able to get recursive field definitions done using this method.... @sfriedel thanks for the hint. Basically, I did:

```
  fieldsThunk := func() graphql.InputObjectConfigFieldMap {
    fields := map[string]*graphql.InputObjectFieldConfig{
      `id`: &graphql.InputObjectFieldConfig{
        Type:        graphql.String,
      },
      ...more fields... 
     }
     return graphql.InputObjectConfigFieldMap(fields)
 }

  object := graphql.NewInputObject(
    graphql.InputObjectConfig{
      Name:   'Person',
      Fields: fields,
    },
  )
```
