### ISSUE TITLE
Cannot access graphql.ResolveParams Source (type interface{} does not support indexing)

### ISSUE THREAD

**Issue by kautsarady** [graphql-go/graphql#400]
//structs
type Book struct {
	Name     string `json:"name"`
	Genre    string `json:"genre"`
	AuthorID int64  `json:"author_id"`
	ID       int64  `json:"id"`
}

type Author struct {
	Name string `json:"name"`
	Age  int64  `json:"age"`
	ID   int64  `json:"id"`
}

// type
var bookType = graphql.NewObject(graphql.ObjectConfig{
	Name: "Book",
	Fields: graphql.Fields{
		"id":    &graphql.Field{Type: graphql.Int},
		"name":  &graphql.Field{Type: graphql.String},
		"genre": &graphql.Field{Type: graphql.String},
	},
})

var authorType = graphql.NewObject(graphql.ObjectConfig{
	Name: "Author",
	Fields: graphql.Fields{
		"id":   &graphql.Field{Type: graphql.Int},
		"name": &graphql.Field{Type: graphql.String},
		"age":  &graphql.Field{Type: graphql.Int},
		"books": &graphql.Field{
			Type: graphql.NewList(bookType),
			Resolve: func(params graphql.ResolveParams) (interface{}, error) {
				p := params.Source["author_id"].(int)
				return getBookByAuthorID(int64(p)), nil
			},
		},
	},
})

The error occur here `p := params.Source["author_id"].(int)`
I've tried to type asserting it to [ ]string and map[string]interface{ } ,  but it returns null (prolly error while asserting)

**Comment by chris-ramon** [comment]
Hi @kautsarady!, thanks for using the lib and reaching us for a question.

If you are trying to access arguments sent via queries, you want to use `params.Args` instead, please refer to this sample:
https://github.com/graphql-go/graphql/blob/cc8e9a91d6b82f2f867446edb51e3f2454b5912b/examples/crud/main.go#L58

Otherwise if your trying to use `params.Source` which points to the parent of the current field, please refer to this sample:
https://github.com/graphql-go/graphql/blob/cc8e9a91d6b82f2f867446edb51e3f2454b5912b/examples/modify-context/main.go#L25

**Comment by kautsarady** [comment]
It solve my problem, Thanks A lot

**Comment by chris-ramon** [comment]
> It solve my problem, Thanks A lot

Awesome, glad to know that @kautsarady, closing the issue.
