### ISSUE TITLE
falsy @deprecated fields in Playground Schema

### ISSUE THREAD

**Issue by sidletsky** [graphql-go/graphql#504]
In Playground under the tab "Schema" I'm getting all the fields and queries being deprecated (without reason) even though in code there are no deprecated fields or queries marked 

Schema in Playground
```
enum MyEnum {
  value1 @deprecated
  value2 @deprecated
  value3 @deprecated
  value4 @deprecated
}
```

code: 
```
myEum := graphql.NewEnum(graphql.EnumConfig{
	Name:        "MyEnum",
	Values:      ValuesToGraphQLEnum(DB.Data()),
	Description: "some description",
	,
	)

func ValuesToGraphQLEnum(values []EnumData) graphql.EnumValueConfigMap {
	enum := make(graphql.EnumValueConfigMap)
	for _, v := range values {
		enum[v.Name] = &graphql.EnumValueConfig{
			Value: v.ID,
		}
	}
	return enum
}
```

**Comment by MarkKremer** [comment]
Introspection schema [according to the spec](https://github.com/graphql/graphql-spec/blob/master/spec/Section%204%20--%20Introspection.md#schema-introspection):
```graphql
type __Field {
  name: String!
  description: String
  args: [__InputValue!]!
  type: __Type!
  isDeprecated: Boolean!
  deprecationReason: String
}
```
[Definition of `Field` in Go](https://github.com/graphql-go/graphql/blob/5fa0612dc4df52a24d62abd7dfd0bd92ec45ba5c/definition.go#L604):
```golang
type Field struct {
	Name              string              `json:"name"` // used by graphlql-relay
	Type              Output              `json:"type"`
	Args              FieldConfigArgument `json:"args"`
	Resolve           FieldResolveFn      `json:"-"`
	DeprecationReason string              `json:"deprecationReason"`
	Description       string              `json:"description"`
}
```
In the Go struct, `DeprecationReason` cannot be nil. It uses an empty string as its empty value ([from which `isDeprecated` is resolved](https://github.com/graphql-go/graphql/blob/5fa0612dc4df52a24d62abd7dfd0bd92ec45ba5c/introspection.go#L308)). The GraphQL schema does allow it to be null. I assume GraphQL Playground only uses the `deprecationReason` to determine if it should add `@deprecated` while ignoring the `isDeprecated` field. This should probably be fixed in the Playground. However, it would also be better if graphql-go returned null if the field is deprecated instead of an empty string.

To do this the field should be made a pointer. Alternatively, a resolver can be added to [the deprecationReason](https://github.com/graphql-go/graphql/blob/5fa0612dc4df52a24d62abd7dfd0bd92ec45ba5c/introspection.go#L313):
```golang
"deprecationReason": &Field{
	Type: String,
	Resolve: func(p ResolveParams) (interface{}, error) {
		if field, ok := p.Source.(*FieldDefinition); ok {
			if field.DeprecationReason != "" {
				return field.DeprecationReason, nil
			}
		}
		return nil, nil
	},
},
```

**Comment by MarkKremer** [comment]
The issue [has also been resolved in graphql-js](https://github.com/graphql/graphql-js/pull/1035) but GraphQL Playground hasn't updated that dependency in 2 years, so...
